//! Renders CONFORMANCE.md from the differ results and the opcode map.

use crate::differ::{CaseReport, Severity, Summary};
use crate::opmap::{self, ImplId};
use std::fmt::Write as _;

pub fn generate(reports: &[CaseReport]) -> String {
    let summary = Summary::from_reports(reports);
    let mut md = String::new();

    writeln!(
        md,
        "# CONFORMANCE — flux-vm implementation family

Generated by `flux-conformance` (branch `conformance-harness`). This harness
documents divergences; it does not fix semantics. Decisions belong to the
flux-vm owners.

**Method.** The repo's nine implementations do not share a wire format, so
the golden corpus is defined as semantic-IR programs (INPUT/PUSH/arith/cmp/
RANGE[lo,hi]/ASSERT/HALT over integers). Each runner compiles the IR into an
implementation's *own* encoding and executes it there, producing a
(result, gas_used, fault) triple. A reference interpreter evaluates the IR in
exact i64 arithmetic as ground truth. The differ flags any disagreement:
implementation vs reference, and implementation vs implementation. Opcode
tables are transcribed per implementation from source and — where the
implementation exposes a byte decoder — machine-verified against it for all
256 byte values."
    )
    .unwrap();

    let _ = writeln!(
        md,
        "\n## 1. Executive summary\n\n- Corpus: **{} cases** ({} runnable implementations + reference interpreter) = {} implementation runs, {} skipped for domain/feature gaps.\n- Divergences: **{} CRITICAL**, {} MAJOR, {} MINOR ({} cases affected), plus {} coverage notes.\n- Opcode bytes with two or more distinct meanings across implementations: **{} of 256**.",
        summary.cases,
        ImplId::ALL.iter().filter(|i| i.runnable()).count(),
        summary.impl_runs,
        summary.impl_skips,
        summary.critical,
        summary.major,
        summary.minor,
        summary.cases_with_divergence,
        summary.info,
        opmap::collisions().len(),
    );

    // ---- Opcode map ----
    md.push_str("\n## 2. Opcode map (byte → meaning)\n\n");
    md.push_str("Rows marked ✅ are machine-verified against the implementation's own decoder for all 256 values (test `opmap_matches_real_decoders`). Others are transcribed from the cited source.\n\n");
    md.push_str("| Implementation | decoded bytes | verification |\n|---|---|---|\n");
    for id in ImplId::ALL {
        let t = opmap::table(id);
        let verif = match id {
            ImplId::Isa | ImplId::Mini | ImplId::Std | ImplId::Edge | ImplId::Thor => {
                "✅ machine-checked vs `from_u8`/`from_byte`"
            }
            ImplId::CoreC | ImplId::MonitorC => {
                "macro table (headers are the decoder; no runtime table to drift)"
            }
            ImplId::VmRs => "match-literal dispatch in source (no decoder fn to check)",
            ImplId::Sat8Fragment => "static — orphan fragment, not compiled anywhere",
            ImplId::PyMaritime => "static — CPU-fallback interpreter inside the demo",
        };
        let _ = writeln!(md, "| {} | {} | {verif} |", id.name(), t.len());
    }

    let collisions = opmap::collisions();
    let class_collisions: Vec<_> = collisions
        .iter()
        .filter(|c| c.distinct_classes > 1)
        .collect();
    let _ = writeln!(
        md,
        "\n**{} bytes carry two or more distinct meanings; {} of those cross semantic classes** (push vs pop vs arithmetic vs ...). Worst offenders, ranked by number of distinct classes then meanings:\n",
        collisions.len(),
        class_collisions.len()
    );
    md.push_str("| byte | meanings across implementations |\n|---|---|\n");
    let mut worst: Vec<&opmap::Collision> = collisions
        .iter()
        .filter(|c| c.distinct_classes > 1)
        .collect();
    worst.sort_by(|a, b| {
        b.distinct_classes
            .cmp(&a.distinct_classes)
            .then(b.distinct_meanings.cmp(&a.distinct_meanings))
            .then(a.byte.cmp(&b.byte))
    });
    for c in worst.iter().take(24) {
        let meanings: Vec<String> = c
            .entries
            .iter()
            .map(|(id, m, cls, _)| format!("{}→**{m}** [{}]", short_name(*id), cls.name()))
            .collect();
        let _ = writeln!(md, "| `0x{:02X}` | {} |", c.byte, meanings.join(" · "));
    }
    let _ = writeln!(
        md,
        "\n*(Full per-implementation tables are in the `flux-conformance` crate source, `src/opmap.rs`, each entry carrying its file:line reference.)*"
    );

    // ---- Divergence log ----
    md.push_str("\n## 3. Divergence log\n\nRoot-cause index: several entries share one cause. (a) **thor's type-strict ASSERT** — `Value::as_bool()` returns `None` for `F64`, so asserting any numeric value fails (D1, D2, D6 and every case that asserts a computed number); (b) **thor's silent-coercion helpers** — `binop`/`binop_bool`/`cmpop` drop values instead of faulting on type mismatch (D3 NaN-div, D4 silent POP); (c) **vm-rs bitwise NOT** on a u8 stack — `!1 = 0xFE` is truthy (D5).\n");
    let mut n = 0usize;
    for r in reports {
        if !r.has_divergence() {
            continue;
        }
        n += 1;
        let _ = writeln!(
            md,
            "\n### D{n}. `{}` ({}) — {}\n\n- Program: `{}`\n- Reference: **{}**\n",
            r.case.name,
            r.case.origin.name(),
            r.case.note,
            r.program_text,
            r.ref_outcome.short()
        );
        md.push_str("| implementation | outcome | gas | encoded (repro) |\n|---|---|---|---|\n");
        for (id, t) in &r.results {
            let gas = t
                .gas_used
                .map(|g| g.to_string())
                .unwrap_or_else(|| "—".into());
            let repro = if t.encoded.is_empty() {
                String::new()
            } else {
                format!("`{}`", t.encoded)
            };
            let _ = writeln!(
                md,
                "| {} | {} | {gas} | {repro} |",
                short_name(*id),
                t.outcome.short()
            );
        }
        md.push_str("\nDivergences:\n");
        for d in &r.divergences {
            if d.severity == Severity::Info {
                continue;
            }
            let _ = writeln!(md, "- **{}**: {}", d.severity.name(), d.detail);
        }
        let notes: Vec<_> = r
            .divergences
            .iter()
            .filter(|d| d.severity == Severity::Info)
            .map(|d| d.detail.clone())
            .collect();
        if !notes.is_empty() {
            let _ = writeln!(md, "\nCoverage: {}", notes.join("; "));
        }
    }

    canonical_proposal(&mut md);
    plainsong_verdict(&mut md, reports);
    method_notes(&mut md);

    md
}

fn short_name(id: ImplId) -> &'static str {
    match id {
        ImplId::CoreC => "c-core",
        ImplId::MonitorC => "c-monitor",
        ImplId::VmRs => "vm-rs",
        ImplId::Isa => "isa",
        ImplId::Mini => "mini",
        ImplId::Std => "std",
        ImplId::Edge => "edge",
        ImplId::Thor => "thor",
        ImplId::Sat8Fragment => "sat8",
        ImplId::PyMaritime => "py-maritime",
    }
}

fn canonical_proposal(md: &mut String) {
    md.push_str(
        r#"
## 4. Proposed canonical opcode table (for the owners to accept/amend)

The harness does not change semantics. This is a proposal, with rationale, so
the sibling owners have one concrete artifact to accept or edit.

**Two sanctioned wire profiles, one per deployment class — not one table for
everything:**

### Profile A — `flux-core` (embedded / safety wire: C core, C monitor, boat lane)

Adopt the C core's assignments verbatim as the canonical embedded wire. It is
the only implementation with a safety story (gas metering, structurally
loop-free ISA, i32 domain, MISRA posture, Cortex-R5 target) and the maritime
demo already targets it.

| byte | meaning | rationale |
|---|---|---|
| `0x00` | NOP | unchanged |
| `0x01`–`0x03` | PUSH_I8 / PUSH_I16 / PUSH_I32 (LE) | width-graded push ladder stays |
| `0x10` | LOAD_INPUT | unchanged |
| `0x1A` | HALT (result = top-of-stack truthiness) | unchanged |
| `0x1B` | ASSERT | unchanged |
| `0x1C` | CHECK_DOMAIN | unchanged |
| `0x1D` | RANGE lo16 hi16 (LE, signed) | **fix the demo, not the VM**: `maritime_constraints.py` must emit 4 operand bytes |
| `0x20`–`0x22` | ADD / SUB / MUL | unchanged |
| `0x23`–`0x25` | EQ / LT / GT | unchanged |
| `0x26`–`0x2A` | BOOL_AND / BOOL_OR / DUP / SWAP / NOT | unchanged |
| `0x04` | PUSH_F32 (LE) — absorbed from the monitor | monitor's only non-overlapping push; C core 0x04 is free |
| `0x2B`–`0x2F` | reserved for SAT8 clamp family if the fragment is ever integrated | keeps SAT8 off the 0x30 row vm-rs already uses |

Required conformances to Profile A:
1. **C monitor** renumbers `PUSH_I32 0x01→0x03`, `POP 0x03→new`, `DUP 0x04→0x28`, `SWAP 0x05→0x29`, `AND/OR 0x20/0x21→0x26/0x27`, `NOT 0x22→0x2A`, `HALT 0xFF→0x1A`. Its CHECK_RANGE_I32 (0x10) is semantically `RANGE + BOOL_AND` and can stay a monitor-side macro.
2. **maritime_constraints.py** emits `RANGE` with two i16 LE operands; its CPU-fallback interpreter is retired in favor of the C core via ctypes.

### Profile B — `flux-rs` (hosted/async: std, edge, thor)

std and thor already agree on every byte they both decode (`0x01` Push,
`0x10`–`0x15` arithmetic, `0x20`–`0x22` logic, `0x30`–`0x35` comparison,
`0x40`s control, `0x50`s+ constraint). Adopt **their shared table**; edge
conforms by moving its comparison block `0x20`–`0x25` → `0x30`–`0x35` and
logic `0x30`–`0x32` → `0x20`–`0x22` (pure renumber; edge's Validate/Tolerance/
Clamp stay at `0x40`–`0x43`). Mandates: f64 immediates **little-endian**
(thor currently reads BE — the only BE encoder in the repo), and a shared
`flux-opcodes` crate so the table cannot drift again (thor already asserts
its opcode counts by test — extend that pattern).

### Explicitly non-wire

- **flux-isa** and **flux-isa-mini**: their `Add = 0x01` numbering collides
  with every push opcode in both profiles. Both are fine *library* ISAs;
  neither should be a wire format. Rename their docs to say so.
- **vm/flux_vm.rs**: a byte-soup R&D VM (`0x01`=POP). Keep as test tissue,
  exclude from wire duty.
- **SAT8 fragment**: integrate under Profile A's reserved band only if it
  ever compiles.

**The one-line version:** byte `0x01` should mean PUSH_I8 on the embedded
wire (Profile A) and Push on the hosted wire (Profile B) — never POP, never
Add, and never two widths of push in the same band.
"#,
    );
}

fn plainsong_verdict(md: &mut String, reports: &[CaseReport]) {
    let plainsong: Vec<&CaseReport> = reports
        .iter()
        .filter(|r| r.case.origin == crate::corpus::Origin::Plainsong)
        .collect();
    let total = plainsong.len();
    let clean = plainsong.iter().filter(|r| !r.has_divergence()).count();
    let divergent: Vec<&CaseReport> = plainsong
        .iter()
        .filter(|r| r.has_divergence())
        .copied()
        .collect();
    let names: Vec<String> = divergent
        .iter()
        .map(|r| {
            format!(
                "`{}` ({})",
                r.case.name,
                r.divergences
                    .iter()
                    .filter(|d| d.severity != Severity::Info)
                    .map(|d| d.severity.name())
                    .collect::<Vec<_>>()
                    .join(",")
            )
        })
        .collect();
    let _ = writeln!(
        md,
        "\n## 5. Plainsong [Perf] predicate verdict (cell-cascade guard use-case)\n\n{} of {} velocity-domain cases ran with zero divergence across every runnable implementation{}.\n\nThe guard shape exercised: `vel ∈ [1,127]` (10 boundary values incl. 0/1/127/128/255), `velocity_std×1000 ∈ [113,257]`, and combined two-predicate guards ANDed at both inclusive bounds. This is exactly the computed-guard shape a sclerotic cell would compile to.\n{}",
        clean,
        total,
        if names.is_empty() {
            String::new()
        } else {
            format!(" — divergent: {}", names.join(", "))
        },
        if divergent.is_empty() {
            "**Verdict: the plainsong-velocity-shaped predicates ran clean.** Once the opcode-scheme question is settled, flux-vm can host cell-cascade guards on today's semantics for the u8 velocity domain."
        } else {
            "**Verdict: NOT clean — see the cases above.** The u8 value domain (vm-rs) and assertion-type strictness (thor) both bite inside the velocity domain itself; fix those before wiring cell-cascade guards."
        }
    );
}

fn method_notes(md: &mut String) {
    md.push_str(
        r#"
## 6. Method notes and known limitations

- The reference interpreter is exact i64; f64 implementations receive
  integer-valued f64s, which are exact up to 2^53 — far above every corpus
  value.
- The C implementations run via FFI from the same test process (compiled
  with the repo CI's `-std=c11 -Wall -Wextra -Werror`).
- vm/flux_vm.rs is compiled as a module of this crate (`#[path]` include):
  previously its tests were invisible to `cargo test --workspace` because a
  virtual workspace root has no package of its own; the same applies to
  `tests/flux_vm_test_harness.rs` and `tests/pipeline_e2e.rs` at the repo
  root, which no CI job builds.
- Gas is only observable where an implementation exposes it (C core). vm-rs
  meters gas internally but has no public accessor; step counters (mini,
  edge, thor) are reported in runner notes, not as gas.
- The SAT8 fragment (`flux_sat8_ops.inc`) is an orphan — it calls
  `flux_pop/flux_push`, which do not exist — so it is mapped statically and
  not executed. `test_sat8` is a prebuilt x86-64 binary with no buildable
  source; it is not run either.
- Divergence severities: CRITICAL = pass/fail flip between implementations
  or vs reference; MAJOR = fault vs boolean-result split; MINOR = differing
  fault kinds; INFO = coverage gaps.

### 6.1 Findings beyond the corpus (verified mechanically where possible)

1. **The maritime demo emits bytecode its own C VM rejects.**
   `src/maritime_constraints.py` encodes RANGE as `[0x1D, lo, hi]` (two
   operand bytes), but the C core's RANGE reads two little-endian i16
   immediates (four operand bytes). Feeding the demo's `check_draft`
   bytecode (`1D 00 06 1B 1A`) to `flux_check` returns FLUX_BAD_BYTECODE —
   proven by the harness test `maritime_demo_bytecode_rejected_by_c_core`.
   The demo passes only because its private Python fallback interpreter
   shares the 2-operand encoding: two implementations agreeing with each
   other and disagreeing with the VM they advertise.
2. **The C monitor defines seven opcodes it never dispatches.** ADD_I32,
   SUB_I32, MUL_I32, CMP_EQ, CMP_LT, CMP_GE and CHECK_DOMAIN are `#define`d
   but absent from the switch — executing them faults with
   FLUX_ERR_INVALID_OPCODE. The runner treats them as unsupported rather
   than recording seven reflexive faults.
3. **The C monitor can vacuously pass.** `flux_monitor_run` returns true
   when the stack bottom is not a bool and no CHECK_* failed — a program
   that ends with a bare value on the stack "passes". There is no ASSERT
   opcode; the runner skips assert-over-value cases rather than record a
   false agreement.
4. **vm/flux_vm.rs `execute` reports silent success on step-budget
   exhaustion.** Its loop returns `Ok(())` after `max_steps` iterations
   without HALT — an infinite (or merely long) program looks successful.
   The harness always passes a generous step budget, so no corpus case
   depends on this.
5. **Three repo test assets are invisible to CI.** The root manifest is a
   virtual workspace, so `tests/flux_vm_test_harness.rs`,
   `tests/pipeline_e2e.rs` and `vm/flux_vm.rs`'s own 44 tests are built by
   no `cargo test --workspace` run. This harness now compiles
   `vm/flux_vm.rs` as a module, putting its tests back under CI; the two
   root `tests/*.rs` files remain unclaimed.
"#,
    );
}
